### ISSUE TITLE
how do I access my REV?

### ISSUE THREAD

**Issue by dckc** [rholang/rholang.github.io#17]
_borrowing from [a RHOC/REV FAQ I made around genesis](https://github.com/rchain-community/RChain-docs/issues/1)_ ...

### Is RHOC in MEW Safe? (yes, assuming...)

If [MEW](https://www.myetherwallet.com/) shows an address that is in `wallets.txt`, then yes, it's safe, provided
  - the last column shows 0 (i.e. a plain Ethereum account, not a smart contract)
  - the RHOC did not get to that account via one of the [scam addresses](https://blog.rchain.coop/blog/2019/05/03/mitigating-the-barcelona-attack/)
    - see also [rchain/rbalance](https://github.com/rchain/rbalance) and [PR 5](https://github.com/rchain/rbalance/pull/5)
  - you have control of the private key for that account

See also

 - [Signing RChain transactions with Metamask and Ledger](https://www.youtube.com/watch?v=8Gkh5_ztqXw) Nov 20, 2019
 - [Jan 27 discussion in #wallet](https://discordapp.com/channels/375365542359465989/479351865457377290/671455869698965525)

#### Is a Ledger hardware wallet safe? (yes, assuming...)

If the wallet you use with your Ledger shows an address in `wallets.txt` then yes, it's safe, though the coop hasn't devoted resources to support that path immediately.

ref:
 - [RCHAIN-3866: Add support for Ethereum personal signature format #2789](https://github.com/rchain/rchain/pull/2789)
 - [Signing RChain transactions with Metamask and Ledger](https://www.youtube.com/watch?v=8Gkh5_ztqXw) Nov 20, 2019

**Comment by SteveHenley** [comment]
### **Wallet Application List:**

- [MRW](https://myrchainwallet.com/)
- [Dappy](https://dappy.tech/)
- [Rui](https://chrome.google.com/webstore/detail/rui%E9%94%90/jkjnjhfcoeoogcdmdhmckfchlbecholg)
- [Capo](https://play.google.com/store/apps/details?id=app.icapo.capo)
- [RNode web client](https://tgrospic.github.io/rnode-client-js/)

**Comment by dckc** [comment]
@SteveHenley thanks for the list of wallet apps!

I edited the link markup, since we can do real hypertext here. cf. [Avoid talking about mechanisms \-\- Hypertext Style Guide](https://www.w3.org/Provider/Style/NoMechanics.html)

**Comment by dckc** [comment]
This issue is obsolete in favor of updates to the [REV Issuance](https://developer.rchain.coop/token-swap) page.

In particular: edits leaning up to 2aeb52b on May 14 https://github.com/rchain/www/blob/master/developer-rchain-coop/src/views/token-swap.hbs
