### ISSUE TITLE
blog byline: by -1

### ISSUE THREAD

**Issue by dckc** [rholang/rholang.github.io#7]
Thanks for merging https://github.com/rholang/rholang.github.io/pull/4 !

Unfortunately, https://rholang.github.io/blog/2020/03/11/debrief-169/ shows an odd byline: "by -1"; i.e.  "Posted 11. March 2020 by -1 min read".

Here's hoping for time to track down what happend to line 4
https://github.com/rholang/rholang.github.io/blame/source/blog/2020-03-11-debrief-169/index.md#L4

**Comment by rholang** [comment]
solved

**Comment by dckc** [comment]
hm. I still see "Posted 11. March 2020 by ~ 1 min read"; maybe it hasn't re-deployed yet?
